### ISSUE TITLE
No printhex.h file in repo

### ISSUE THREAD

**Issue by DarkHalo117** [rstemmer/id3edit#26]
Had issues building package. First issue was the clang dep wasn't installed so it threw zlib errors. Now I'm having an issue where printhex.h is not found and I tried installing bsdmainutils to get their hexdump header. Still having an issue.

Output:
Compiling ./crc32.c …
Compiling ./encoding/crc.c …
Compiling ./encoding/size.c …
Compiling ./encoding/text.c …
Compiling ./extheader.c …
Compiling ./frameflags.c …
Compiling ./id3v2.c …
Compiling ./id3v2frame.c …
Compiling ./main.c …
./main.c:12:10: fatal error: 'printhex.h' file not found
#include <printhex.h>
         ^~~~~~~~~~~~
1 error generated.
Compiling ./rawfile.c …
/usr/bin/ld: cannot find -lprinthex: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rstemmer** [comment]
I'm sorry, that is actually an issue with the documentation.

In the very unlikely case (not ironic) someone scrolls down the readme to the _Installation_ section: [README→Installation](https://github.com/rstemmer/id3edit#installation) a detailed and complete installation instruction is given. Including dependencies.

This should be included in the Quick-Install guide at the very beginning of the readme.
I will fix this.

**Solution**
You need to install [libprinthex](https://github.com/rstemmer/libprinthex) first. That is the missing dependency providing the `printhex.h` header.

**Comment by rstemmer** [comment]
I hope this solved your problem. If not feel free to reopen the ticket.

Thank you for reporting this issue.
